name: krave
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_messaging: ^15.0.0
  cloud_functions: ^5.0.0
  pdf: ^3.10.0
  flutter_local_notifications: ^17.0.0
  razorpay_flutter: ^1.3.6
  provider: ^6.0.5
  intl: ^0.19.0
  fluttertoast: ^8.2.5
  cached_network_image: ^3.3.0
  file_picker: ^8.1.4
  uuid: ^4.5.1
  printing: ^5.13.4
  image_picker: ^1.1.2
  http: ^1.2.1
  cupertino_icons: ^1.0.8
  collection: ^1.18.0
  firebase_app_check: ^0.3.2+10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/secrets.properties
